### ISSUE TITLE
Add a key to quit the application

### ISSUE THREAD

**Issue by ben-pearson** [K-42/python#5]
As fun as CTRL+C is, perhaps a 'q' could quit the application

**Comment by K-42** [comment]
Haven't a clue how to do this. Do I set it as a command-line argument? Haven't read up much on that yet so let me know and I'll delve in.

**Comment by ben-pearson** [comment]
I'm not sure off the top of my head but in principle:

while (input() != 'q')
{
do your application
}

**Comment by K-42** [comment]
Oh I see! That'll work :p


Get Outlook for Android






On Thu, Jun 16, 2016 at 9:14 PM +0100, "givenuponlife" <notifications@github.com> wrote:





I'm not sure off the top of my head but in principle:

while (input() != 'q')
{
do your application
}

On 16 June 2016 at 20:26, K-42 <notifications@github.com> wrote:

> Haven't a clue how to do this. Do I set it as a command-line argument?
> Haven't read up much on that yet so let me know and I'll delve in.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/K-42/python/issues/5#issuecomment-226587971>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AMzzWnxiMAyUwlljE2i1vDRcNbDB2SmGks5qMaNxgaJpZM4I17T2>
> .
>


---

**Comment by givenuponlife** [comment]
Did you just tell me to get Outlook for Android? :-D

**Comment by K-42** [comment]
Yis! Self advertising email app. I could change it.....


Get Outlook for Android






On Thu, Jun 16, 2016 at 10:51 PM +0100, "givenuponlife" <notifications@github.com> wrote:





Reopened #5.

---
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/K-42/python/issues/5#event-695269750

**Comment by K-42** [comment]
Added a quit option to the menu and then added a way to get to the menu from the loop. Using input() blocked the loop while it waited for a keypress. I set up a separate thread that checks for a press of the ESC key and then changes a variable that quits the main loop.
